defmodule LfgBot.Repo.Migrations.AddDiscordDataToSessions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:sessions) do
      modify :player_reserve, {:array, :map}, default: []
      add :message_id, :text, null: false
      add :channel_id, :text, null: false
      add :guild_id, :text, null: false
      add :leader_user_id, :text, null: false
      add :leader_user_name, :text, null: false
    end
  end

  def down do
    alter table(:sessions) do
      remove :leader_user_name
      remove :leader_user_id
      remove :guild_id
      remove :channel_id
      remove :message_id
      modify :player_reserve, {:array, :map}, default: nil
    end
  end
end