defmodule LfgBot.Repo.Migrations.AddMessageId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:registered_guild_channel), :intro_channel_id, to: :channel_id

    alter table(:registered_guild_channel) do
      add :message_id, :text
    end

    drop_if_exists unique_index(:registered_guild_channel, [:guild_id, :intro_channel_id],
                     name: "registered_guild_channel_unique_server_index"
                   )

    create unique_index(:registered_guild_channel, [:guild_id, :channel_id, :message_id],
             name: "registered_guild_channel_unique_server_index"
           )
  end

  def down do
    drop_if_exists unique_index(:registered_guild_channel, [:guild_id, :channel_id, :message_id],
                     name: "registered_guild_channel_unique_server_index"
                   )

    create unique_index(:registered_guild_channel, [:guild_id, :intro_channel_id],
             name: "registered_guild_channel_unique_server_index"
           )

    alter table(:registered_guild_channel) do
      remove :message_id
    end

    rename table(:registered_guild_channel), :channel_id, to: :intro_channel_id
  end
end