defmodule LfgBot.Repo.Migrations.ChangeUniqueServerRegistration do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:registered_guild_channel, [:channel_id, :guild_id, :message_id],
                     name: "registered_guild_channel_unique_server_index"
                   )

    create unique_index(:registered_guild_channel, [:guild_id, :channel_id],
             name: "registered_guild_channel_unique_server_index"
           )
  end

  def down do
    drop_if_exists unique_index(:registered_guild_channel, [:guild_id, :channel_id],
                     name: "registered_guild_channel_unique_server_index"
                   )

    create unique_index(:registered_guild_channel, [:channel_id, :guild_id, :message_id],
             name: "registered_guild_channel_unique_server_index"
           )
  end
end