defmodule LfgBot.Repo.Migrations.AddLogTimestamp do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:logs) do
      add :inserted_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:logs) do
      remove :inserted_at
    end
  end
end