defmodule LfgBot.Repo.Migrations.AddLog do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:logs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :type, :text
      add :data, :text
    end
  end

  def down do
    drop table(:logs)
  end
end