defmodule LfgBot.Repo.Migrations.RequiredMessageId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:registered_guild_channel) do
      modify :intro_message_id, :text, null: false
    end
  end

  def down do
    alter table(:registered_guild_channel) do
      modify :intro_message_id, :text, null: true
    end
  end
end